name = "ENVPack"
uuid = "27417be4-8871-48a1-a0f5-6afa2b22e277"
authors = ["N5N3 <2642243996@qq.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
